# Generated by Django 6.0.4 on 2026-04-22 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=30, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('user_id_value', models.CharField(max_length=150)),
                ('user_password', models.CharField(max_length=150)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved by Support', 'Resolved by Support'), ('Sent to Developer', 'Sent to Developer'), ('Developer In Progress', 'Developer In Progress'), ('Closed', 'Closed'), ('Reopened', 'Reopened')], max_length=30)),
                ('support_decision', models.CharField(choices=[('Solved by Support', 'Solved by Support'), ('Moved to Development', 'Moved to Development')], max_length=30)),
                ('is_sent_to_developer', models.BooleanField(default=False)),
                ('support_remark', models.TextField(blank=True, null=True)),
                ('developer_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.emailconfig')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masters.module')),
                ('reported_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masters.reportedto')),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masters.submodule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('cc_emails', models.TextField(blank=True, null=True)),
                ('mail_subject', models.CharField(max_length=300)),
                ('mail_body', models.TextField()),
                ('send_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/')),
                ('original_file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
            ],
        ),
    ]
