# Generated by Django 6.0.1 on 2026-04-25 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_department'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='masters.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='masters.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='masters.department'),
            preserve_default=False,
        ),
    ]
