# Generated by Django 6.0.1 on 2026-04-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_emaillog_department_ticket_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='division_name',
            field=models.CharField(default='Default Division', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_id_value',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
