# Generated by Django 6.0.1 on 2026-05-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved by Support', 'Resolved by Support'), ('Sent to Developer', 'Sent to Developer'), ('Developer In Progress', 'Developer In Progress'), ('Closed', 'Closed'), ('Reopened', 'Reopened')], default='Open', max_length=30),
        ),
    ]
