# Generated by Django 6.0.1 on 2026-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bug_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
